[package]
name = "day5"
version = "0.1.0"
authors = ["Robert Tully <robert.tully@drakon.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
